api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "capped-reward"
type = "function"
uid = "16785a68-718a-6b56-1355-d61ea96b54149320fbb0"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
